[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python3", "gcc", "g++", "make", "pkg-config", "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg"]

[phases.install]
cmds = [
    "npm ci --only=production",
    "npm install sharp --build-from-source"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && npm start"

[vars]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_BUILD_FROM_SOURCE = "true"

[static]
[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10